Add preliminary object detection to perception pipeline
diegomtzg/InFrame pull request #2
Opened 2020-03-24 23:17 UTC by diegomtzg

Includes temporary test script similar to what system controller would do

2020-03-24 23:43 UTC, ikekilinc requested changes
Looks great! Can you delete "perception/temp.txt" before merge?
The file exists only as a placeholder so that Github registers the folder structure.

2020-03-25 15:12 UTC, diegomtzg commented
I did! That change is at the bottom of the commit. I probably should have included that in the commit msg.

2020-03-25 15:32 UTC, ikekilinc commented
Looks good now!

2020-03-25 15:33 UTC, ikekilinc approved these changes

2020-03-25 15:33 UTC, merged